FROM oven/bun:1.2.21

WORKDIR /var/www/hackron-web

COPY ./turbo.json ./
COPY ./package.json ./bun.lock ./
COPY apps/web ./apps/web
COPY packages ./packages

RUN bun install --lockfile

RUN bunx turbo build --filter=web...

WORKDIR /apps/web

EXPOSE 3000
CMD ["bun", "start"]